#!/bin/bash
#
# Service script for a Node.js application running under Forever.
#
# This is suitable for Fedora, Red Hat, CentOS and similar distributions.
# It will not work on Ubuntu or other Debian-style distributions!
#
# There is some perhaps unnecessary complexity going on in the relationship between
# Forever and the server process. See: https://github.com/indexzero/forever
#
# 1) Forever starts its own watchdog process, and keeps its own configuration data 
# in /var/run/forever.
#
# 2) If the process dies, Forever will restart it: if it fails but continues to run, 
# it won't be restarted.
#
# 3) If the process is stopped via this script, the pidfile is left in place; this 
# helps when issues happen with failed stop attempts.
#
# 4) Which means the check for running/not running is complex, and involves parsing 
# of the Forever list output.
#
# chkconfig: 345 80 20

# Source function library.
NAME=ticketchain_backend

SOURCE_DIR=/home/ubuntu/ticketchain-backend
SOURCE_FILE=ticketchain.js

user=ubuntu
pidfile=/var/run/$NAME.pid
logfile=/var/log/$NAME.log
forever_dir=/var/run/

node=nodejs
forever=forever
sed=sed

export PATH=$PATH:/usr/local/bin/nodejs
export NODE_PATH=$NODE_PATH:/usr/share/npm/node_modules/

start() {
     echo "Starting $NAME node instance: "

          if [ "$foreverid" == "" ]; then
                    # Create the log and pid files, making sure that 
                    # the target use has access to them
                    touch $logfile
                    chown $user $logfile

                    touch $pidfile
                    chown $user $pidfile

                    # Launch the application
                    cd $SOURCE_DIR
                    $forever start -p --pidFile $pidfile -l $logfile -a -d $SOURCE_FILE
                    RETVAL=$?
          else
               echo "Instance already running"
                    RETVAL=0
                    fi
}

stop() {
     echo -n "Shutting down $NAME node instance : "
          if [ "$foreverid" != "" ]; then
               #TODO: graceful shutdown...
               #$node $SOURCE_DIR/scripts/prepareForStop.js
               $forever -p $forever_dir --pidfile $pidfile -l $logfile stop $foreverid
          else
               echo "Instance is not running";
     fi
          RETVAL=$?
}

if [ -f $pidfile ]; then
     read pid < $pidfile
     echo "Found PID: " $pid
else
     echo "Can not read pid file: " $pidfile
     pid=""
fi

if [ "$pid" != "" ]; then
     # Gnarly sed usage to obtain the foreverid.
     sed1="/$pid\]/p"
     sed2="s/.*\[\([0-9]\+\)\].*\s$pid\.*/\1/g"
     foreverid=`$forever list | sed -n $sed1 | sed $sed2`

     echo "Found foreverid: " $foreverid
else
     echo "Can not find foreverid: " $foreverid
     foreverid=""
fi

case "$1" in
start)
     start
     ;;
stop)
     stop
     ;;
status)
     #$forever list -p ${pidfile}
     $forever list 
     ;;
*)
     echo "Usage:  {start|stop|status}"
     exit 1
     ;;
esac

exit $RETVAL
